import { jsPDF } from "jspdf";
import type { AnalysisResult, UserProfile } from "@/store/useStore";

/* ─── Color Palette (Dark Premium Theme) ─── */
const BG: [number, number, number] = [8, 12, 28];         // deep navy
const BG2: [number, number, number] = [14, 20, 45];       // section bg
const CARD: [number, number, number] = [20, 30, 60];      // card bg
const CYAN: [number, number, number] = [0, 200, 255];     // primary accent
const CYAN2: [number, number, number] = [0, 140, 220];    // darker cyan
const WHITE: [number, number, number] = [240, 248, 255];  // near-white text
const GREY: [number, number, number] = [120, 145, 180];   // muted text
const DIM: [number, number, number] = [60, 80, 120];      // very dim text

const STATUS_COLORS: Record<string, [number, number, number]> = {
  Excellent: [0, 210, 130],
  Good: [0, 180, 255],
  Improvable: [255, 140, 60],
};

export function generateReport(
  analysis: AnalysisResult,
  profile: UserProfile,
): void {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 16;
  const contentWidth = pageWidth - 2 * margin;
  let y = 0;

  /* ─── Helpers ─── */

  const setFont = (
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = WHITE,
  ) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
  };

  const centerText = (
    text: string,
    yPos: number,
    size: number,
    style: "normal" | "bold" = "normal",
    color: [number, number, number] = WHITE,
  ) => {
    setFont(size, style, color);
    const w = doc.getTextWidth(text);
    doc.text(text, (pageWidth - w) / 2, yPos);
  };

  const fillPage = (color: [number, number, number]) => {
    doc.setFillColor(...color);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
  };

  const drawRect = (
    x: number, yy: number, w: number, h: number,
    color: [number, number, number],
    rounded = 0,
  ) => {
    doc.setFillColor(...color);
    if (rounded > 0) doc.roundedRect(x, yy, w, h, rounded, rounded, "F");
    else doc.rect(x, yy, w, h, "F");
  };

  const drawStrokeRect = (
    x: number, yy: number, w: number, h: number,
    color: [number, number, number],
    lineWidth = 0.5,
    rounded = 0,
  ) => {
    doc.setDrawColor(...color);
    doc.setLineWidth(lineWidth);
    if (rounded > 0) doc.roundedRect(x, yy, w, h, rounded, rounded, "S");
    else doc.rect(x, yy, w, h, "S");
  };

  const drawArc = (
    cx: number, cy: number, r: number,
    startAngle: number, endAngle: number,
    color: [number, number, number],
    lineWidth = 2,
  ) => {
    doc.setDrawColor(...color);
    doc.setLineWidth(lineWidth);
    const steps = 40;
    const dA = (endAngle - startAngle) / steps;
    for (let i = 0; i < steps; i++) {
      const a1 = startAngle + dA * i;
      const a2 = startAngle + dA * (i + 1);
      doc.line(
        cx + r * Math.cos(a1),
        cy + r * Math.sin(a1),
        cx + r * Math.cos(a2),
        cy + r * Math.sin(a2),
      );
    }
  };

  const checkPageBreak = (needed = 20) => {
    if (y + needed > pageHeight - 16) {
      addFooter();
      doc.addPage();
      fillPage(BG);
      y = 16;
    }
  };

  const addFooter = () => {
    // Footer band
    drawRect(0, pageHeight - 14, pageWidth, 14, BG2);
    setFont(7, "normal", DIM);
    const footerText = "Generated by LooksMax AI  •  For informational purposes only  •  " +
      new Date().toISOString().split("T")[0];
    const fw = doc.getTextWidth(footerText);
    doc.text(footerText, (pageWidth - fw) / 2, pageHeight - 5.5);
  };

  const sectionHeader = (title: string, icon = "▸") => {
    checkPageBreak(22);
    // Left accent bar
    drawRect(margin, y, 3, 10, CYAN);
    // Section bg card
    drawRect(margin + 4, y - 1, contentWidth - 4, 12, CARD, 2);
    setFont(10, "bold", CYAN);
    doc.text(`${icon}  ${title.toUpperCase()}`, margin + 10, y + 7.5);
    y += 18;
  };

  /* ══════════════════════════════════════
     PAGE 1 — COVER / HEADER
  ══════════════════════════════════════ */
  fillPage(BG);

  // Top gradient band (simulated with layered rects)
  for (let i = 0; i < 10; i++) {
    const alpha = 1 - i / 10;
    const r = Math.round(BG2[0] + (CARD[0] - BG2[0]) * alpha);
    const g = Math.round(BG2[1] + (CARD[1] - BG2[1]) * alpha);
    const b = Math.round(BG2[2] + (CARD[2] - BG2[2]) * alpha);
    drawRect(0, i * 5, pageWidth, 5, [r, g, b] as [number,number,number]);
  }

  // LOOKSMAX AI — brand title
  y = 22;
  centerText("LOOKSMAX AI", y, 28, "bold", CYAN);
  y += 10;

  // Thin cyan underline
  doc.setDrawColor(...CYAN);
  doc.setLineWidth(0.8);
  doc.line(margin + 30, y, pageWidth - margin - 30, y);
  y += 7;

  centerText("AESTHETIC ANALYSIS REPORT", y, 10, "bold", GREY);
  y += 6;
  centerText(
    new Date(analysis.timestamp).toLocaleDateString("en-US", {
      year: "numeric", month: "long", day: "numeric",
    }),
    y, 8, "normal", DIM,
  );
  y += 14;

  /* ── User info card ── */
  if (profile.name || profile.goal) {
    drawRect(margin, y, contentWidth, profile.name && profile.goal ? 18 : 11, CARD, 4);
    drawStrokeRect(margin, y, contentWidth, profile.name && profile.goal ? 18 : 11, CYAN2, 0.4, 4);
    let cardY = y + 8;
    if (profile.name) {
      setFont(9, "bold", GREY);
      doc.text("NAME", margin + 6, cardY);
      setFont(9, "bold", WHITE);
      doc.text(profile.name, margin + 22, cardY);
      cardY += 7;
    }
    if (profile.goal) {
      setFont(9, "bold", GREY);
      doc.text("GOAL", margin + 6, cardY);
      setFont(9, "normal", WHITE);
      doc.text(profile.goal.charAt(0).toUpperCase() + profile.goal.slice(1), margin + 22, cardY);
    }
    y += (profile.name && profile.goal ? 18 : 11) + 12;
  }

  /* ── Score Ring ── */
  const cx = pageWidth / 2;
  const cy = y + 30;
  const ringR = 26;

  // Outer dark ring
  drawArc(cx, cy, ringR, Math.PI * 0.75, Math.PI * 2.25, CARD, 6);
  // Score fill ring (proportion of 10)
  const scoreRatio = Math.min(1, analysis.overallScore / 10);
  const arcEnd = Math.PI * 0.75 + scoreRatio * (Math.PI * 1.5);
  drawArc(cx, cy, ringR, Math.PI * 0.75, arcEnd, CYAN, 3);
  // Inner circle background
  drawRect(cx - 18, cy - 18, 36, 36, BG, 18);

  // Score text
  setFont(20, "bold", WHITE);
  const scoreStr = `${analysis.overallScore}`;
  const sw = doc.getTextWidth(scoreStr);
  doc.text(scoreStr, cx - sw / 2, cy + 7);

  setFont(7, "normal", GREY);
  const tenStr = "/ 10";
  const tw = doc.getTextWidth(tenStr);
  doc.text(tenStr, cx - tw / 2, cy + 14);

  y = cy + ringR + 12;

  // Tier badges
  const tierLabel = `CURRENT TIER: ${analysis.tier.toUpperCase()}`;
  const tlw = 90;
  drawRect((pageWidth - tlw) / 2 - 5, y - 5, tlw + 10, 11, CARD, 3);
  centerText(tierLabel, y + 3, 8, "bold", CYAN);
  y += 12;

  const potLabel = `POTENTIAL: ${analysis.potentialScore} / 10  (${analysis.potentialTier})`;
  centerText(potLabel, y + 3, 8, "normal", GREY);
  y += 16;

  /* ══════════════════════════════════════
     FEATURE BREAKDOWN
  ══════════════════════════════════════ */
  sectionHeader("Feature Breakdown", "▸");

  const barTrackW = 80;
  const barH = 5;

  for (const item of analysis.radarData) {
    checkPageBreak(16);

    // Row background
    drawRect(margin, y - 4, contentWidth, 13, CARD, 2);

    // Trait name
    setFont(8.5, "bold", WHITE);
    doc.text(item.trait, margin + 4, y + 4);

    // Track
    const barX = margin + 68;
    drawRect(barX, y - 1, barTrackW, barH, [20, 35, 65] as [number,number,number], 2);

    // Fill
    const fillW = Math.max(3, (item.current / 100) * barTrackW);
    // Gradient simulation: two overlapping fills
    drawRect(barX, y - 1, fillW, barH, CYAN2, 2);
    drawRect(barX, y - 1, fillW * 0.4, barH, CYAN, 2);

    // Scores
    setFont(7.5, "normal", GREY);
    doc.text(`${item.current}`, barX + barTrackW + 4, y + 4);
    setFont(7.5, "normal", DIM);
    doc.text(`→ ${item.potential}`, barX + barTrackW + 14, y + 4);

    y += 15;
  }

  y += 4;

  /* ══════════════════════════════════════
     DETAILED ANALYSIS
  ══════════════════════════════════════ */
  sectionHeader("Detailed Analysis", "◆");

  for (const trait of analysis.detailedTraits) {
    checkPageBreak(36);

    const rowH = 8 + (doc.splitTextToSize(trait.detail, contentWidth - 12) as string[]).length * 4.5 + 10;
    drawRect(margin, y - 2, contentWidth, rowH, CARD, 3);
    drawStrokeRect(margin, y - 2, contentWidth, rowH, [30, 50, 90] as [number,number,number], 0.3, 3);

    // Trait name
    setFont(9, "bold", WHITE);
    doc.text(`● ${trait.name}: ${trait.value}`, margin + 5, y + 5.5);

    // Status badge
    const [sr, sg, sb] = STATUS_COLORS[trait.status] || [100, 120, 160];
    const statusLabel = ` [${trait.status}] `;
    const labelW = doc.getTextWidth(statusLabel);
    const badgeX = pageWidth - margin - labelW - 6;
    doc.setFillColor(sr, sg, sb, 0.15);
    drawRect(badgeX - 2, y, labelW + 4, 7, [sr * 0.15, sg * 0.15, sb * 0.15] as [number,number,number], 2);
    doc.setTextColor(sr, sg, sb);
    setFont(7.5, "bold");
    doc.setTextColor(sr, sg, sb);
    doc.text(statusLabel, badgeX, y + 5.5);

    y += 10;

    // Detail text
    setFont(7.5, "normal", GREY);
    const lines: string[] = doc.splitTextToSize(trait.detail, contentWidth - 12) as string[];
    doc.text(lines, margin + 6, y);
    y += lines.length * 4.5 + rowH - 10 - lines.length * 4.5 + 4;
    y += 8;
  }

  /* ══════════════════════════════════════
     ACTION PLAN
  ══════════════════════════════════════ */
  const improvableTraits = analysis.detailedTraits.filter((t) => t.improvable);

  if (improvableTraits.length > 0) {
    checkPageBreak(24);
    sectionHeader("Recommended Action Plan", "✦");

    const recommendations: Record<string, string[]> = {
      "Facial Symmetry": [
        "Practice proper tongue posture (mewing) for balanced development",
        "Sleep on your back to avoid facial compression",
        "Chew evenly on both sides",
      ],
      "Jawline Definition": [
        "Mewing: Keep tongue pressed against roof of mouth consistently",
        "Masseter training with mastic gum (3×/week, 100 reps)",
        "Reduce body fat percentage to reveal underlying jaw structure",
        "Gua sha massage along the jawline for lymphatic drainage",
      ],
      "Canthal Tilt": [
        "Orbital bone massage techniques (gentle, consistent)",
        "Proper posture to avoid forward head tilt",
        "Adequate sleep to reduce under-eye puffiness",
      ],
      "Skin Texture": [
        "Double cleanse morning and night",
        "Daily SPF 50+ sunscreen (non-negotiable)",
        "Vitamin C serum in the morning for brightening",
        "Retinol at night for cell turnover (start 0.1%, build to 0.3%)",
        "Weekly chemical exfoliation (AHA/BHA)",
      ],
      "Facial Dimorphism": [
        "Jawline resistance training with mastic gum or jaw trainer",
        "Mewing for forward maxilla growth",
        "Compound exercises (deadlifts, squats) to boost testosterone",
        "Adequate protein intake for muscle and bone development",
      ],
    };

    for (const trait of improvableTraits) {
      checkPageBreak(28);

      const recs = recommendations[trait.name] || [];
      const blockH = 10 + recs.length * 8 + 4;
      drawRect(margin, y - 2, contentWidth, blockH, CARD, 3);
      // Cyan left stripe
      drawRect(margin, y - 2, 3, blockH, CYAN, 0);

      setFont(9, "bold", CYAN);
      doc.text(`▸  ${trait.name}`, margin + 8, y + 5.5);
      y += 11;

      for (const rec of recs) {
        checkPageBreak(10);
        setFont(8, "normal", GREY);
        const recLines: string[] = doc.splitTextToSize(`  •  ${rec}`, contentWidth - 16) as string[];
        doc.text(recLines, margin + 8, y);
        y += recLines.length * 5.5;
      }
      y += 10;
    }
  }

  /* ── Footer on last page ── */
  addFooter();

  doc.save(`LooksMax-Report-${new Date().toISOString().split("T")[0]}.pdf`);
}
